### PR TITLE
Minor progress towards playability

### PR DESCRIPTION
**Pull request by jayaddison**
Ciao @dodomorandi!

I've been trying to get an x64 build of QC running under Linux, and found your fork which seems to have the most progress.

This branch contains a few further commits - these are (I hope) 'clean' modifications that should be relatively safe and reliable.

There's also a more experimental [branch](https://github.com/jayaddison/quadrilateral-cowboy/tree/maintenance/incorporate-tdm) where I'm attempting to bring in some upstream x64 support from The Dark Mod and Dhewm3.

I can get to the point where the main QC menu opens, and sound effects work there, but I've not yet been able to load a map successfully.  I'm pretty sure it's mostly down to pointers and typecasting as you mention in your commits.

### CODE REVIEW

**Comment by dodomorandi** [comment]
Thank you so much for your contribution!

As you can see, I tried to hack & play with the code, and at the time it was something too big for me. I would be really happy if this could be a starting point for something useful!

In any case, your changes are more than reasonable.

About the problem running the game: try to compile with address/ub sanitizer in order to catch something very wrong that is happening around. Generally it is not straightforward to understand what is going on, but surely it points you to the right direction.
Thank you again!

**Comment by jayaddison** [comment]
You're welcome - and wow, yep - I see a lot of problems after enabling the ub sanitizer.  Thanks; I didn't know about that tool until now.  That hopefully helps get to the next stage soon!

**Comment by jayaddison** [comment]
By the way - there is now an 'official' upstream repository from Blendo - with 64-bit Linux support!  https://github.com/blendogames/quadrilateralcowboy

**Comment by jayaddison** [comment]
@dodomorandi this comment is basically off-topic spam, but I was wondering: if you have time, could you let me know how bad the Italian on https://www.reciperadar.com/ is (or refer someone who might be interested to review it)?  The site should auto-detect browser locale, but the results may be.. sub-optimal..

**Pull request merged**
